require("plugins_config/treesitter_conf")
require("plugins_config/lsp_conf")
require("plugins_config/cmp_conf")
require("plugins_config/please_conf")
require("plugins_config/barbar_conf")
require("plugins_config/nvimtree_conf")
require("plugins_config/mason_lspconfig_conf")
