repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.4.0
    hooks:
      - id: stylua
        types: [lua]

  - repo: local
    hooks:
      - id: act-lint
        name: act / lint.yml
        language: system
        pass_filenames: false
        always_run: true
        entry: act -W .github/workflows/lint.yml

      - id: nix-develop
        name: nix develop
        language: system
        pass_filenames: false
        always_run: true
        entry: nix develop --ignore-environment --keep HOME --command echo "ok"

      - id: act-nvim-deprecations
        name: act / nvim-deprecations.yml
        language: system
        pass_filenames: false
        always_run: true
        entry: act -W .github/workflows/nvim-deprecations.yml

      - id: act-nvim-plugins
        name: act / nvim-plugins.yml
        language: system
        pass_filenames: false
        always_run: true
        entry: act -W .github/workflows/nvim-plugins.yml

      - id: act-python-lint
        name: act / python-lint.yml
        language: system
        pass_filenames: false
        always_run: true
        entry: act -W .github/workflows/python-lint.yml

      - id: act-sway-config
        name: act / sway-config.yml
        language: system
        pass_filenames: false
        always_run: true
        entry: act -W .github/workflows/sway-config.yml
