Listen localhost:10631
Browsing Off
WebInterface Yes
<Location />
Order allow,deny
Allow localhost
</Location>
<Location /admin>
Order allow,deny
Allow localhost
</Location>
<Policy default>
<Limit All>
Order deny,allow
</Limit>
</Policy>
