[package]
name = "common"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rustix = { version = "1", features = ["fs", "system"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tempfile = "3"
