name: Actionlint

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install actionlint
        run: |
          version=$(basename "$(curl -sSL -o /dev/null -w '%{url_effective}' \
            https://github.com/rhysd/actionlint/releases/latest)")
          curl -sSL \
            "https://github.com/rhysd/actionlint/releases/download/${version}/actionlint_${version#v}_linux_amd64.tar.gz" \
            | sudo tar -xz -C /usr/local/bin actionlint

      - name: Run actionlint
        run: actionlint
