name: Actions Security

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install zizmor
        run: |
          curl -sSL \
            "https://github.com/zizmorcore/zizmor/releases/latest/download/zizmor-$(uname -m)-unknown-linux-gnu.tar.gz" \
            | sudo tar -xz -C /usr/local/bin zizmor

      - name: Run zizmor
        run: zizmor --no-online-audits .github/workflows/
