name: Format Lint

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/*.md'

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install yamllint
        run: pipx install yamllint

      - name: Run yamllint
        run: export PATH="$(pipx environment --value PIPX_BIN_DIR):$PATH"; git ls-files '*.yml' '*.yaml' | xargs yamllint -c .config/yamllint/config.yaml

  taplo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install taplo
        run: |
          curl -sSL \
            "https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-$(uname -m).gz" \
            | gunzip \
            | sudo tee /usr/local/bin/taplo > /dev/null
          sudo chmod +x /usr/local/bin/taplo

      - name: Run taplo
        run: git ls-files '*.toml' | xargs taplo lint --config .config/taplo/taplo.toml

  editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install editorconfig-checker
        run: |
          curl -sSL \
            "https://github.com/editorconfig-checker/editorconfig-checker/releases/latest/download/ec-linux-amd64.tar.gz" \
            | sudo tar -xz -C /usr/local/bin --strip-components=1 bin/ec-linux-amd64
          sudo mv /usr/local/bin/ec-linux-amd64 /usr/local/bin/editorconfig-checker

      - name: Run editorconfig-checker
        run: editorconfig-checker -config .config/editorconfig-checker/config.json
