name: Build Docker Image With Nix Shell

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - run: df -h
      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
      - run: df -h
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
      - name: Build Docker image
        run: |
          nix-channel --add https://nixos.org/channels/nixos-24.05 nixpkgs
          nix-channel --update
          nix-build .config/nix/docker.nix
      - name: Load Docker image
        run: |
          ./result | docker load
      - name: Push Docker image
        run: docker push nuhotetotniksvoboden/bashrc:latest
