name: Build Nix Shell

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
      - name: Install dependencies
        run: |
          nix-shell .config/nix/dev.nix --run "echo Nix initialised successfully!"
  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
      - name: Install dependencies
        run: |
          nix-shell .config/nix/dev.nix --run "echo Nix initialised successfully!"
