name: Build Docker Image With Nix Shell

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
      - name: Build Docker image
        run: |
          # Also change .config/nix/*.nix and
          # ~/.local/share/bin/init-user-env.sh when changing the channel
          nix-channel --add https://nixos.org/channels/nixos-24.11 nixpkgs
          nix-channel --update
          nix-build .config/nix/docker.nix
      - name: Load Docker image
        run: |
          ./result | docker load
      - name: Push Docker image
        run: docker push nuhotetotniksvoboden/bashrc:latest
      - name: Remove Nix Garbage
        run: nix-collect-garbage -d
