name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs make cmake git
      - name: Run test script
        run: |
          chmod +x scripts/test.sh
          ./scripts/test.sh
